### ISSUE TITLE
Support AutoSearchPath, etc

### ISSUE THREAD

**Issue by burner1024** [FakelsHub/F2_ProtoManager#10]
It seems that latest sfall additions (`AutoSearchPath`, `DataLoadOrderPatch`, etc) aren't supported yet?

**Comment by FakelsHub** [comment]
Программа не читает какие-либо конфиги игры, все пути заданы жеcтко и не меняются (кроме папки куда сохранять протопиты).

**Comment by burner1024** [comment]
И не будет?

**Comment by FakelsHub** [comment]
Незнаю :-)

**Comment by burner1024** [comment]
Ну смотри сам.

**Comment by FakelsHub** [comment]
Чтобы такое сделать надо написать много кода. :-)

**Comment by burner1024** [comment]
Ну что может добавишь поддержку?

**Comment by FakelsHub** [comment]
Что уже почти год прошел, вот время летит.
Сейчас пока не до этого, другие планы есть.

**Comment by FakelsHub** [comment]
Может просто добавить менюшку, где ты будешь указывать дополнительные папки/дат файлы откуда читать?
А то что-то не очень хочется заморачиваться с автоматическим поиском файлов и проверять с соблюдением приоритетов.

**Comment by burner1024** [comment]
А разве в менюшке не нужно будет указывать приоритеты и потом согласно им читать, т.е. то же самое?

**Comment by FakelsHub** [comment]
Нужно, но это менее геморройнее чем выстраивать это все автоматически по алфавиту/по номерам.

**Comment by burner1024** [comment]
Да в общем это и так некритично. Если никто не жалуется, значит люди не используют новую систему. Хотя конечно, как они будут использовать, если она не поддерживается...
Мне так, раз в пару месяцев что-нибудь отредактировать. Не влом и руками достать.

**Comment by FakelsHub** [comment]
Для следующей версии добавил поиск файлов во всех .dat файлах или папках.
