### ISSUE TITLE
Using Fo1 skill calculations

### ISSUE THREAD

**Issue by Lexx2k** [FakelsHub/F2_ProtoManager#11]
Would it be possible to implement a switch to go from Fo2 skill calculations to Fo1 skill calculations? 

OR (that's an even better idea) make the tool read out the Sfall Skills.ini file and apply the formula changes accordingly. 

That would make it a bit easier for me to check critter skill values without having to double check with ingame debug scripts.

**Comment by FakelsHub** [comment]
I already did this, you only need to wait for the release.
Support for sfall is planned later.

**Comment by FakelsHub** [comment]
[Here you can take compiled exe file](https://ci.appveyor.com/project/FakelsHub/f2-protomanager/build/artifacts).

**Comment by Lexx2k** [comment]
Thanks. Did some test runs and it seems to work exactly as it should.
