### ISSUE TITLE
hp calculation differences Fo1/2

### ISSUE THREAD

**Issue by Lexx2k** [FakelsHub/F2_ProtoManager#12]
I just noticed that my Ian proto has 50hp when using the Fo2 calculation settings, but 46hp when using the Fo1 calculation.

The wiki says that base hp is calculated with 15 + STR + (2*END) for both Fo1 and Fo2.

Is there a bug going on here or is the wiki wrong (again)?

**Comment by FakelsHub** [comment]
Here bug.
