### ISSUE TITLE
Windows Defender reporting MSIL/Remcos.ED!MTB

### ISSUE THREAD

**Issue by blackpaulillyria** [FakelsHub/F2_ProtoManager#13]
The latest Windows Defender is reporting this as MSIL/Remcos.ED!MTB.
Can you investigate and fix this?

**Comment by FakelsHub** [comment]
This is similar to the fact that antiviruses are buggy (false triggering of heuristic analysis).
A couple of days ago, my antivirus also reported that it found a Trojan in this exe file.
I checked my system, no viruses or Trojans were found.
I compiled a new version v1.2.2 and still the antivirus thinks it's a Trojan.

Some people have similar problems after compiling.
https://github.com/ferib/D2R-Offline/discussions/61

**Comment by Lexx2k** [comment]
Yup, mine went off as well. Had to set an exception for the dll.

**Comment by ChronoTempus** [comment]
I sent a sample to Defender team with a proof that is build from sources and there is no trojan, they answered that it will remain in their system as the compiled version follows mentioned malware pattern (this is only for release version, debug one doesn't trigger anything).

**Comment by FakelsHub** [comment]
manufacturers of ativirus software do not know how to make ativiruses, they know how to identify malware based on patterns. fuck tell me such an antivirus.

**add the program to the exception and use it calmly.**
