### ISSUE TITLE
possible anti-virus issue

### ISSUE THREAD

**Issue by QuantumApprentice** [FakelsHub/F2_ProtoManager#14]
Just wanted to give you a heads up about this, looks like some anti-virus's are flagging the exe:
https://www.virustotal.com/gui/file/dd4eecb8bca7d8d7220dd5946a1449aec833fbc74550254300602519295fe0bc/detection

This appears to be the same with both v1.2.1 and v1.2.2.
Original discussion here:
https://youtu.be/vCPc1gxPtKk

**Comment by FakelsHub** [comment]
next version 1.3 may be virus-free))
I do not know what code does not like these filthy antiviruses.

**Comment by QuantumApprentice** [comment]
I'd like to help if I can, I posted on the nma forums about this, but I've read that there's a way to submit an executable to antivirus websites and have them officially declare the file as clean.  
Have you had any experience doing this?
Is it possible for me to contribute by doing this?

**Comment by FakelsHub** [comment]
> Have you had any experience doing this?

no.

> Is it possible for me to contribute by doing this?

yes.
