### ISSUE TITLE
Problems with setting up 1.3.0 for Fallout 1

### ISSUE THREAD

**Issue by NovaRain** [FakelsHub/F2_ProtoManager#15]
I installed a fresh copy of 1.3.0 on Fallout 1 (with TeamX patches). After setting up the paths, I got the error about `sndlist.lst` when starting the manager:
![err1](https://user-images.githubusercontent.com/8564973/127415232-a5681c55-94f7-49fa-b600-fecb28086d7e.png)

I clicked OK, and clicked the "Run" button on the interface that appears next:
![startui](https://user-images.githubusercontent.com/8564973/127415397-c6b3914f-7cce-4ceb-ab30-7b4daa5437fd.png)

But now it's stuck at some "value of 110" error:
![err2](https://user-images.githubusercontent.com/8564973/127415610-18d7980b-28be-4efc-800e-6cf93e0b8e8a.png)

My configuration settings:
![config](https://user-images.githubusercontent.com/8564973/127416385-96bb143a-25eb-4127-99ce-27fe6f701c9d.png)

If I close and restart the manager, it repeats the steps of "sndlist.lst error -> click Run -> value of 110 error". The older 1.2.2 runs fine with my FO1.

**Comment by FakelsHub** [comment]
> But now it's stuck at some "value of 110" error:

Copy the contents of the error.log file (in root folder) here.

**Comment by NovaRain** [comment]
> 
> Copy the contents of the error.log file (in root folder) here.

OK, here:
```
   at System.Windows.Forms.ProgressBar.set_Value(Int32 value)
   at Main.Main()
   at SplashScreen.Run()Value of '110' is not valid for 'Value'. 'Value' should be between 'minimum' and 'maximum'.
Parameter name: Value
```

**Comment by FakelsHub** [comment]
**FIXED**
