### ISSUE TITLE
Don't select items on mouse hover

### ISSUE THREAD

**Issue by phobos2077** [FakelsHub/F2_ProtoManager#2]
Когда водишь мышкой по списку прототипов - они зачемто выделяются. 
Это очень необычное поведение и оно раздражает :)

**Comment by FakelsHub** [comment]
Там на этом что-то вроде завязано, посмотрю - если ничего то уберу, или сделаю настройку отключалку.

**Comment by FakelsHub** [comment]
Проверил, завязано на среднею клавишу мышки - одним кликом сразу открывается окно для редактирования. 
так же на клавишу Ctrl-E, наводишь и нажимаешь хоткей, без всяких кликов.

**Comment by phobos2077** [comment]
Все равно с точки зрения UX это сомнительное решение. Можно же сделать открывание по одиночному клику но без предварительного автовыделения.

**Comment by FakelsHub** [comment]
Кому как.
В след версии для не любителей авто выделений будет отключалка.
