### ISSUE TITLE
"Index was outside the bounds of the array" error

### ISSUE THREAD

**Issue by konkun1998** [FakelsHub/F2_ProtoManager#3]
Hi !
When i try to launch a manager "Index was outside the bounds of the array" error shows up. 
PS. Sorry for my english ( not my native language ).

**Comment by FakelsHub** [comment]
On which game Fallout2 (mod) do you run the editor?

**Comment by konkun1998** [comment]
Fallout 2 RP 2.3.3 steam. Editor worked when i launched it for a first time but now this error pops up.

**Comment by konkun1998** [comment]
I also have fo2tweaks and home sweet home mod.

**Comment by FakelsHub** [comment]
Try the newer [version](https://yadi.sk/d/uExXEYsE3Lpmqf), in case of an error in the editor folder, the error.log file will be created, copy the contents of the log file and put it here.

**Comment by konkun1998** [comment]
Ok editor now works. I just fucked up ammo weight value and now I must reinstall f2.
