### ISSUE TITLE
Перепутаны dr/dt в броне

### ISSUE THREAD

**Issue by burner1024** [FakelsHub/F2_ProtoManager#8]
Только для EMP правильные значения, для остальных показателей перепутаны.
![captura de pantalla de 2018-11-13 21-46-27](https://user-images.githubusercontent.com/1279852/48420732-a043c100-e78d-11e8-9acc-466fbdc495de.png)
Edit: а может и для emp тоже, я не помню что там должно быть.

**Comment by FakelsHub** [comment]
ага точно, спасибо.

**Comment by FakelsHub** [comment]
Fixed.
